### ISSUE TITLE
Items align in vertical slider

### ISSUE THREAD

**Issue by andrey-hohlov** [rcbyr/keen-slider#137]
If we use vertical slider with slidesPerView = slides count the last slide will be cut.

Look at this example https://codesandbox.io/s/naughty-shirley-t3zd5?file=/index.html
Then open styles.css, uncomment line 10 ```align-content: flex-start;``` and look again.

Minimal flex behavior reproduction: https://jsfiddle.net/andrhohlov/4ypcev18/

```html
<div class="container">
  <div class="item">1</div>
  <div class="item">2</div>
  <div class="item">3</div>
  <div class="item">4</div>
</div>
```

```css
.container {
  display: flex;
  flex-wrap: wrap;
  height: 430px;
  width: 80px;
  background: gray;
  /* align-content: flex-start; */
}

.item {
  width: 100%;
  height: 80px;
  background: yellow;
}
```

I think it should be added to keen-slider styles.
