### ISSUE TITLE
Cumulative Layout Shift

### ISSUE THREAD

**Issue by lucasoz** [rcbyr/keen-slider#146]
Hi! I am getting bad score in my pagespeed insights because keen-slider render the slider after app loaded.
I am not sure how we could fix that :cry

This is your spacing example with 6 containers
![ezgif com-gif-maker](https://user-images.githubusercontent.com/18173423/137065186-b18dfa75-cda7-4235-8908-c1300b11c15e.gif)
:

**Comment by rizkysyazuli** [comment]
You can copy the generated styles into your own css to fix this.

```css
.keen-slider__slide {
  min-width: calc(100% + 0px);
  max-width: calc(100% + 0px);
  transform: translate3d(0, 0, 0);
}
```
