### ISSUE TITLE
Provide SCSS within NPM package

### ISSUE THREAD

**Issue by ohepworthbell** [rcbyr/keen-slider#20]
`node-sass@v5` does not watch or properly import CSS, but converts any such calls to `import(example.css);`. Whilst Webpack handles this change gracefully, CSS files are not similarly handled when importing directly using `node-sass` (using something like Gulp and without any additional plugins).

I see in the `src/` for this repo there is a SCSS file - it would be great if this was included as part of the `npm` package for import, as well as a CSS file.

The stylesheet can also be converted to actual SCSS too, nesting the selectors and removing the prefixes (which can ultimately be handled by the end user IMO, allowing them to negate any prefixes they don't want/need), turning the SCSS into this (as a quick, untested example):

```scss
.keen-slider {
  display: block;
  overflow: hidden;
  position: relative;
  user-select: none;
  touch-action: pan-y;
  -webkit-tap-highlight-color: transparent;
  
  &__slide {
    position: absolute;
    overflow: hidden;
    width: 100%;
    min-height: 100%;
  }

  &--vertical &__slide {
    min-height: auto;
  }
}
```

P.S. Thanks for the plugin!
