### ISSUE TITLE
Q: Scale active slide

### ISSUE THREAD

**Issue by d3v4nt** [rcbyr/keen-slider#341]
Hey guys, first of all thanks for the amazing library, it's really simple and awesome. However I'm struggling when trying to achieve next effect:

![Screenshot 2023-06-18 at 11 56 32](https://github.com/rcbyr/keen-slider/assets/33395021/8de02204-33fc-47e8-9bfa-b34e1b72a856)

### Effect description:

- All slides besides the active one have same width.
- Active one visually should be as if it were scaled to 125%.
- Active slide ideally should cover un-active one next to it.

I've obviously tried all css variations but no luck. One example:
```css
    .keen-slider {
        overflow-x: hidden !important;
        overflow-y: visible !important;
    }

    .keen-slider__slide {
        transform-origin: left center;
        overflow: visible !important;
        z-index: 0;
    }

    .keen-slider__slide.active {
        z-index: 10;
    }

    .keen-slider__slide.active img {
        transform: scale(1.25);
    }
```

> As you may know specifying two axis overflows doesn't work very well in css

But a scrollbar appears and only `overflow: visible !important` fixes the issue with a drawback of showing all the slides horizontally which is not ideal:

<img width="214" alt="Screenshot 2023-06-18 at 11 59 49" src="https://github.com/rcbyr/keen-slider/assets/33395021/c5124034-87da-4b25-8a29-1899ff646c69">

So I was thinking maybe a custom plugin would help here? 
Would appreciate any suggestions,
Cheers.
