### ISSUE TITLE
Slides are stretched to available width if the number of slides < slidesPerView

### ISSUE THREAD

**Issue by flackeryy** [rcbyr/keen-slider#97]
I'm facing one issue where I specify a `slidesPerView`.  Generally it works fine.

![image](https://user-images.githubusercontent.com/23479556/109806197-16091a80-7c2d-11eb-8a74-f1c8fb6c2e8d.png)

But in case if I have slides count < slidesPerView, for example, I receive 1 item from the API, it stretches a single slide to full available width, even if `slidesPerView` set to `3`, so the card starts looking incorrectly.

![image](https://user-images.githubusercontent.com/23479556/109806782-c6771e80-7c2d-11eb-95f0-7df065760086.png)

Instead, I expected to see the single card still keep 1/3 of the slider width (keep `spacing` as well).

I tried to get the desired behavior by calculating "missing" slides and render an empty `<div className="keen-slider__slide" />`. For instance, if I receive only 1 item, I will render 2 empty `<div className="keen-slider__slide" />` so the count of `children` is equal to `slidesPrevView`.

![image](https://user-images.githubusercontent.com/23479556/109807452-967c4b00-7c2e-11eb-925b-6a625ee87f9d.png)

And it might be a solution, but things become complicated when I also have a specified `breakpoints` property and want to display `slidesPerView: 2` and `sliderPerView: 1` on smaller screens. In this case, need to create an unnecessary logic 
for calculating a count of empty `<div className="keen-slider__slide" />` that should be rendered.

Are there are any ways or ideas on how to get the described behavior? It would be really great to have a config property like `keepSlideWidth: true/false` that keeps the slide width depends on `slidesPerView` even if the number of slides < `slidesPerView`

Thanks.

**Comment by ruijdacd** [comment]
Hey @flackeryy 

Currently there is a PR open, that fixes this problem https://github.com/rcbyr/keen-slider/pull/87. Not quite sure if it'll get merged, but I do appreciate the idea of having a config property that would enable/disable this feature, as opposed to changing implementation for all users and use cases.

@rcbyr can you give us some input around this feature? Would love to hear back from you around the likeliness of having a feature that can allow us to build this layout.

**Comment by flackeryy** [comment]
@ruijdacd Thanks for your reply. I can see some workarounds around this issue in #52, so will try to use them for now. But yes, I think it will be good to have the ability to configure this option based on developers' own requirements.

**Comment by lukethacoder** [comment]
if you're looking for a css only solution, this worked for my use case.

```css
.keen-slider__slide {
  min-width: 100% !important;
  max-width: 100% !important;
}
@media (min-width: 768px) {
  .keen-slider__slide {
    min-width: calc(50% - 4px) !important;
    max-width: calc(50% - 4px) !important;
  }
}
@media (min-width: 1024px) {
  .keen-slider__slide {
    min-width: calc(33% - 4px) !important;
    max-width: calc(33% - 4px) !important;
  }
}
```

obviously adjust for your `slidesPerView` value and breakpoints
